import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";

import { compareText } from "./lib/deterministic-order.js";

export const MAXIMUM_FILE_LINES: number = 500;
const AUTOGENERATED_FILE_PATHS: ReadonlySet<string> = new Set<string>([
  "bun.lock",
  "website/bun.lock",
]);

export type FileCandidate = {
  readonly content: Uint8Array;
  readonly path: string;
};

export type OversizedFileException = {
  readonly reason: string;
  readonly sha256: string;
};

export type FileLineAudit = {
  readonly checkedTextFiles: number;
  readonly errors: readonly string[];
  readonly pinnedExceptions: number;
};

export const OVERSIZED_FILE_EXCEPTIONS: ReadonlyMap<string, OversizedFileException> = new Map<
  string,
  OversizedFileException
>([
  [
    "supabase/migrations/20260808224428_hosted_control_plane.sql",
    {
      reason: "immutable migration already applied to production",
      // biome-ignore lint/security/noSecrets: This is a public SHA-256 integrity digest.
      sha256: "75a52409a330687f4b0003e65ee84b9727664bcd904ac84446c77fdf84043750",
    },
  ],
]);

function decodeText(content: Uint8Array): string | null {
  if (content.includes(0)) return null;
  try {
    const decoder: TextDecoder = new TextDecoder("utf-8", { fatal: true });
    return decoder.decode(content);
  } catch {
    return null;
  }
}

export function countFileLines(content: string): number {
  if (content === "") return 0;
  const segments: number = content.split(/\r\n|\r|\n/gu).length;
  return content.endsWith("\n") || content.endsWith("\r") ? segments - 1 : segments;
}

function sha256(content: Uint8Array): string {
  return createHash("sha256").update(content).digest("hex");
}

export function auditFileLines(
  candidates: readonly FileCandidate[],
  exceptions: ReadonlyMap<string, OversizedFileException> = OVERSIZED_FILE_EXCEPTIONS,
): FileLineAudit {
  const errors: string[] = [];
  const seenPaths: Set<string> = new Set<string>();
  let checkedTextFiles: number = 0;
  let pinnedExceptions: number = 0;

  for (const candidate of candidates) {
    if (seenPaths.has(candidate.path)) {
      throw new Error(`File census contains duplicate path '${candidate.path}'`);
    }
    seenPaths.add(candidate.path);
    if (AUTOGENERATED_FILE_PATHS.has(candidate.path)) continue;
    const content: string | null = decodeText(candidate.content);
    if (content === null) continue;
    checkedTextFiles += 1;
    const lines: number = countFileLines(content);
    if (lines <= MAXIMUM_FILE_LINES) continue;

    const exception: OversizedFileException | undefined = exceptions.get(candidate.path);
    if (exception === undefined) {
      errors.push(
        `${candidate.path} has ${lines} lines; authored text files may contain at most ${MAXIMUM_FILE_LINES}`,
      );
      continue;
    }
    const actualHash: string = sha256(candidate.content);
    if (actualHash !== exception.sha256) {
      errors.push(
        `${candidate.path} has ${lines} lines and no longer matches its pinned SHA-256; ` +
          `expected ${exception.sha256}, received ${actualHash}`,
      );
      continue;
    }
    pinnedExceptions += 1;
  }

  const missingExceptions: string[] = [...exceptions.keys()].filter(
    (path: string): boolean => !seenPaths.has(path),
  );
  if (missingExceptions.length > 0) {
    errors.push(
      `Pinned oversized-file exceptions are absent from the census: ${missingExceptions.join(", ")}`,
    );
  }
  return { checkedTextFiles, errors, pinnedExceptions };
}

export function repositoryFileCandidates(
  workspace: string = process.cwd(),
): readonly FileCandidate[] {
  const output: string = execFileSync(
    "git",
    ["ls-files", "-z", "--cached", "--others", "--exclude-standard"],
    { cwd: workspace, encoding: "utf8" },
  );
  const paths: string[] = output
    .split("\0")
    .filter((path: string): boolean => path !== "")
    .sort(compareText);
  const candidates: FileCandidate[] = [];
  for (const path of paths) {
    const absolutePath: string = join(workspace, path);
    if (!existsSync(absolutePath)) continue;
    if (!lstatSync(absolutePath).isFile()) continue;
    candidates.push({ content: readFileSync(absolutePath), path });
  }
  return candidates;
}

export function runFileLineAudit(workspace: string = process.cwd()): FileLineAudit {
  return auditFileLines(repositoryFileCandidates(workspace));
}

function main(): void {
  try {
    const audit: FileLineAudit = runFileLineAudit();
    if (audit.errors.length > 0) {
      for (const error of audit.errors) process.stderr.write(`File-size gate: ${error}\n`);
      process.exitCode = 1;
      return;
    }
    process.stdout.write(
      `File-size gate passed for ${audit.checkedTextFiles} text files ` +
        `with ${audit.pinnedExceptions} hash-pinned exception.\n`,
    );
  } catch (error: unknown) {
    const message: string = error instanceof Error ? error.message : String(error);
    process.stderr.write(`File-size gate failed: ${message}\n`);
    process.exitCode = 1;
  }
}

if (import.meta.main) main();
